// Shared normalization data for quiz generation.
// These lists help reject weak questions, noisy PDF text, and generic answers.

// Quiz size used by generator and fallback paths.
const QUIZ_QUESTION_COUNT = 10;

// Frontend-supported question types.
const QUIZ_TYPES = ["multiple_choice", "true_false", "multiple_select", "reorder", "open_answer"];

// Generic question stems that usually mean the quiz is weak.
const GENERIC_QUESTION_PATTERNS = [
  "the source mentions",
  "which of these terms appear in the source",
  "order the key ideas from the source",
  "name one key idea from the source",
  "which concept is most central",
  "what is the primary goal of",
  "which layer usually handles",
  "what is the biggest risk here",
];

// Meta/template phrases rejected during question normalization.
const META_QUESTION_PATTERNS = [
  "the source mentions",
  "the source",
  "as mentioned",
  "like is mentioned",
  "nearby",
  "the source mentions x",
  "which term best completes",
  "which statement best explains",
  "this statement matches",
  "matches the explanation",
  "which interpretation is most consistent",
  "which term best completes this idea",
  "which of these terms appear in the source",
  "which of these terms",
  "after studying",
  "learning objectives",
  "correct answer",
  "incorrect",
  "inc orrect",
  "the correct answer",
];

// Generic words that are too weak as standalone answers.
const GENERIC_KEYWORDS = new Set([
  "case",
  "cases",
  "diagram",
  "diagrams",
  "system",
  "user",
  "users",
  "overview",
  "concept",
  "details",
  "application",
  "apply",
  "applies",
  "source",
  "open",
  "lesson",
  "material",
  "instructional",
  "distance",
  "intellectual",
  "objectives",
  "students",
  "teaching",
  "knowledge",
  "page",
  "break",
  "manages",
  "provides",
  "contains",
  "support",
  "record",
  "responsible",
  "step",
  "next",
  "previous",
  "practice",
  "tour",
  "welcome",
  "documentation",
  "language",
  "list",
  "lists",
  "called",
  "however",
  "approach",
  "value",
  "values",
  "time",
  "times",
  "gmt",
  "utc",
  "published",
  "publication",
  "updated",
  "response",
  "responses",
  "reference",
  "argument",
  "arguments",
  "message",
  "messages",
  "belongs",
  "receive",
  "receives",
  "indicate",
  "indicates",
  "feature",
  "stable",
  "rule",
  "correspond",
  "corresponds",
  "passed",
  "throws",
  "allows",
  "appears",
  "still",
  "passing",
  "updated",
  "response",
  "if",
  "since",
  "also",
  "einen",
  "eine",
  "einer",
  "einem",
  "eines",
  "der",
  "die",
  "das",
  "dass",
  "den",
  "dem",
  "des",
  "sich",
  "sein",
  "sind",
  "werden",
  "wird",
  "heißt",
  "heisst",
  "handelt",
  "möglich",
  "moeglich",
  "möglichen",
  "moeglichen",
  "mögliche",
  "moegliche",
  "vorhanden",
  "bringt",
  "bringen",
  "gibt",
  "korrekt",
  "durchführung",
  "durchfuehrung",
  "kann",
  "können",
  "koennen",
  "nach",
  "zum",
  "zur",
  "beim",
  "vom",
]);

// Weak single terms rejected for open answers.
const WEAK_SINGLE_ANSWER_TERMS = new Set([
  "type",
  "function",
  "method",
  "property",
  "parameter",
  "argument",
  "value",
  "time",
  "gmt",
  "utc",
  "published",
  "updated",
  "response",
  "message",
  "called",
  "passing",
  "eine",
  "einer",
  "einem",
  "einen",
  "sein",
  "sich",
  "sind",
  "werden",
  "wird",
  "heißt",
  "heisst",
  "handelt",
  "möglich",
  "moeglich",
  "möglichen",
  "moeglichen",
  "mögliche",
  "moegliche",
  "vorhanden",
  "korrekt",
  "durchführung",
  "durchfuehrung",
  "nach",
  "dass",
  "kann",
  "können",
  "koennen",
]);

// PDF lines that are usually headers, footers, or metadata.
const PDF_NOISE_PATTERNS = [
  /^(page|seite)\s+\d+$/i,
  /^(block|unit)\s+\d+\s*$/i,
  /^(block|unit)\s+\d+\b.*$/i,
  /^(published|published\s+time|publication\s+date|updated\s+time|modified\s+time)\s*:/i,
  /\b(?:published|published\s+time|publication\s+date|updated\s+time|modified\s+time)\s*:\s*.*\b(?:gmt|utc)\b/i,
  /^(copyright|all rights reserved|isbn)\b/i,
  /^(dr\.|prof\.|mr\.|mrs\.|ms\.)\s+[A-Z]/i,
  /^(mobile application development|basics of android application|pgdca\s+\d+)\b/i,
  /^(knowledge management and research organization|instructional design and editing)\b/i,
  /^(book|course|programme|program)\s*$/i,
  /^kotlin\s+language\s+documentation\b/i,
  /^welcome\s+to\s+our\s+tour\s+of\s+kotlin/i,
  /^kotlin\s+\d+(?:\.\d+)+\s*$/i,
  /^version\s+\d+(?:\.\d+)+\s*$/i,
  /^[.\s]{8,}\d+\s*$/,
  /^.{2,90}\.{5,}\s*\d+\s*$/,
];

// Website boilerplate patterns removed before quiz generation.
const NAVIGATION_JUNK_PATTERNS = [
  /courses\s*tutorials\s*interview/i,
  /interview\s*prep\s*android\s*tutorial/i,
  /tutorial\s*interview\s*questions\s*projects/i,
  /last\s+updated\s*:\s*\d{1,2}\s+[a-z]{3}/i,
  /geeksforgeeks|w3schools|tutorialspoint/i,
  /w\s*3\s*schools\s+is\s+(?:optimized|powered)/i,
  /examples might be simplified to improve reading and learning/i,
  /tutorials,? references,? and examples are constantly reviewed/i,
  /cannot warrant full correctness/i,
  /send us an e-?mail|report an error|make a suggestion/i,
];

// Common stopwords used by keyword extraction and fuzzy deduplication.
const STOPWORDS = new Set([
  "the", "and", "for", "with", "that", "this", "from", "are", "was", "were", "been", "have", "has",
  "had", "into", "over", "under", "your", "their", "there", "about", "what", "when", "where", "which",
  "will", "would", "could", "should", "can", "may", "might", "than", "then", "them", "they", "his", "her",
  "our", "you", "but", "not", "all", "any", "more", "most", "some", "such", "only", "each", "also",
  "here", "while", "because", "between", "after", "before", "through", "during", "these", "those", "who",
  "whom", "whose", "how", "why", "theirs", "ours", "it", "its", "is", "am", "be", "as", "at", "by",
  "of", "on", "or", "to", "in", "a", "an",
  // German stopwords keep extracted concepts from becoming "Eine", "Der", or "Dass".
  "der", "die", "das", "den", "dem", "des", "ein", "eine", "einer", "einem", "einen", "eines",
  "und", "oder", "aber", "auch", "nur", "nicht", "kein", "keine", "keiner", "keinem", "keinen",
  "ist", "sind", "war", "waren", "sein", "seine", "seiner", "seinem", "seinen", "wird", "werden",
  "wurde", "wurden", "hat", "haben", "hatte", "hatten", "kann", "können", "koennen", "konnte",
  "im", "in", "am", "an", "auf", "aus", "bei", "beim", "mit", "ohne", "von", "vom", "zu", "zum",
  "zur", "für", "fuer", "nach", "vor", "über", "ueber", "unter", "zwischen", "durch", "als",
  "dass", "wenn", "weil", "wie", "was", "wer", "wo", "warum", "welche", "welcher", "welches",
  "welchen", "welchem", "dies", "diese", "dieser", "dieses", "diesen", "diesem", "jeder", "jede",
  "jedes", "man", "sich", "es", "er", "sie", "wir", "ihr", "du", "ich", "dabei", "dann", "dazu",
  "hier", "dort", "also", "eben", "noch", "mehr", "weniger", "alle", "allen", "alles",
  "heißt", "heisst", "handelt", "möglich", "moeglich", "möglichen", "moeglichen", "mögliche", "moegliche", "vorhanden",
  "bringt", "bringen", "gibt", "korrekt", "durchführung", "durchfuehrung"
]);

module.exports = {
  GENERIC_KEYWORDS,
  GENERIC_QUESTION_PATTERNS,
  META_QUESTION_PATTERNS,
  NAVIGATION_JUNK_PATTERNS,
  PDF_NOISE_PATTERNS,
  QUIZ_QUESTION_COUNT,
  QUIZ_TYPES,
  STOPWORDS,
  WEAK_SINGLE_ANSWER_TERMS,
};
