// =============================================================
// FILE LOCATION: client/src/pages/CourseManager.tsx
// REPLACE existing file entirely
// Header handled by Layout.tsx — no header here
// AI nodes = red border (matches playground)
// =============================================================

import { useParams, useNavigate } from "react-router-dom";
import { useState, useEffect, useCallback } from "react";
import axios from "axios";
import {
  ArrowLeft, Users, BookOpen,
  Copy, Check, Globe, Trash2,
  Plus, Search, X, ChevronDown, ChevronRight } from "lucide-react";

// Color constants for consistent UI styling
const CN = {
  blue: "#1E6FFF",
  blueDark: "#1557CC",
  red: "#E63027",
  green: "#3A9E3F",
  yellow: "#F5C518",
};

// A simple button to copy text to clipboard with a visual feedback state
function CopyBtn({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  
  const handleCopy = () => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <button onClick={handleCopy} className="p-1 hover:bg-gray-100 rounded transition-colors">
      {copied ? <Check size={14} style={{ color: CN.green }} /> : <Copy size={14} className="text-gray-400" />}
    </button>
  );
}

// Reusable tab button — active tab gets a blue background, inactive stays transparent
function TabBtn({ label, active, onClick }: { label: string; active: boolean; onClick: () => void }) {
  return (
    <button 
      onClick={onClick}
      className="px-4 py-2.5 text-sm font-bold rounded-xl transition-all flex-1 md:flex-none"
      style={{ 
        background: active ? CN.blue : "transparent", 
        color: active ? "white" : "#6B7280" 
      }}
    >
      {label}
    </button>
  );
}

// Inline topic search + add panel, shown inside the Nodes tab
function AddTopicPanel({
  courseId,
  onTopicAdded
}: {
  courseId: string;
  onTopicAdded: (newTopics: any[]) => void;
}) {
  const [mode, setMode] = useState<"search" | "manual">("search");
  const [search, setSearch] = useState("");
  const [results, setResults] = useState<any[]>([]);
  const [adding, setAdding] = useState(false);
  const [addingTopicId, setAddingTopicId] = useState<string | null>(null);

  // Manual State
  const [manualName, setManualName] = useState("");
  const [manualDesc, setManualDesc] = useState("");
  const [manualFile, setManualFile] = useState<File | null>(null);
  const [manualUrl, setManualUrl] = useState("");
 
  const handleSearch = async (q: string) => {
    setSearch(q);
    if (q.length > 2) {
      const res = await axios.get(`http://localhost:3000/api/wiki/search?q=${q}`);
      setResults(res.data);
    } else { setResults([]); }
  };
 
  const handleAdd = async (topic: any) => {
    setAdding(true);
    setAddingTopicId(topic.id);
    try {
      const token = localStorage.getItem("token");
      const res = await axios.post("http://localhost:3000/api/topics", {
        name: topic.label,
        description: topic.description || "",
        courseId,
        wikidataId: topic.id,
        generateSubtopics: true,
      }, { headers: { Authorization: `Bearer ${token}` } });

      const mainTopic = res.data;
      const autoSubtopics = (mainTopic?.autoGeneratedSubtopics || []).map((sub: any) => ({
        ...sub,
        prerequisites: sub.prerequisites || [{ id: mainTopic.id, name: mainTopic.name }]
      }));
      onTopicAdded([mainTopic, ...autoSubtopics]);

      setSearch("");
      setResults([]);
    } catch (err) { console.error(err); } finally {
      setAdding(false);
      setAddingTopicId(null);
    }
  };

  const handleManualSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!manualName) return;
    setAdding(true);

    try {
      const token = localStorage.getItem("token");
      const formData = new FormData();
      formData.append("name", manualName);
      formData.append("description", manualDesc);
      formData.append("courseId", courseId);
      formData.append("generateSubtopics", "false");
      if (manualUrl) formData.append("sourceUrl", manualUrl);
      if (manualFile) formData.append("pdf", manualFile);

      const res = await axios.post("http://localhost:3000/api/topics", formData, {
        headers: { 
          Authorization: `Bearer ${token}`,
          "Content-Type": "multipart/form-data" 
        }
      });

      setManualName("");
      setManualDesc("");
      setManualFile(null);
      setManualUrl("");
      onTopicAdded([res.data]);
    } catch (err) { console.error(err); } finally { setAdding(false); }
  };
 
  return (
    <div className="bg-white dark:bg-gray-800 rounded-2xl border dark:border-gray-700 p-6 shadow-sm">
      <div className="flex items-center justify-between mb-4">
        <p className="text-xs font-bold text-gray-400 uppercase tracking-widest">Neues Thema hinzufügen</p>
        <div className="flex bg-gray-100 dark:bg-gray-900 p-1 rounded-lg">
          <button 
            onClick={() => setMode("search")}
            className={`px-3 py-1 text-[10px] font-bold rounded-md transition-all ${mode === "search" ? "bg-white dark:bg-gray-700 text-blue-600 shadow-sm" : "text-gray-400"}`}
          >
            WIKIDATA SUCHE
          </button>
          <button 
            onClick={() => setMode("manual")}
            className={`px-3 py-1 text-[10px] font-bold rounded-md transition-all ${mode === "manual" ? "bg-white dark:bg-gray-700 text-blue-600 shadow-sm" : "text-gray-400"}`}
          >
            MANUELL / PDF
          </button>
        </div>
      </div>
 
      {mode === "search" ? (
        <div className="relative">
          <Search className="absolute left-3 top-3 text-gray-400" size={16} />
          <input
            className="w-full pl-9 pr-4 py-2.5 rounded-xl border dark:border-gray-700 dark:bg-gray-900 dark:text-white text-sm outline-none focus:ring-2 focus:ring-blue-500 transition-all"
            placeholder="Nach Themen suchen (z.B. Quantenphysik)..."
            value={search}
            onChange={(e) => handleSearch(e.target.value)}
          />
          {results.length > 0 && (
            <div className="mt-3 border dark:border-gray-700 rounded-xl overflow-hidden divide-y dark:divide-gray-700 max-h-48 overflow-y-auto custom-scrollbar">
              {results.map((r) => (
                <div
                  key={r.id}
                  className="w-full px-4 py-3 hover:bg-blue-50 dark:hover:bg-blue-900/20 transition-colors flex items-start justify-between gap-3"
                >
                  <div className="flex items-start gap-3">
                    <Plus size={16} className="mt-0.5 text-blue-500" />
                    <div>
                      <p className="font-semibold text-sm dark:text-white">{r.label}</p>
                      <p className="text-[10px] text-gray-500 line-clamp-1">{r.description}</p>
                    </div>
                  </div>
                  <div>
                    <button
                      onClick={() => handleAdd(r)}
                      disabled={adding}
                      className="px-3 py-1.5 text-[11px] font-bold rounded-lg border border-blue-200 text-blue-700 hover:bg-blue-100 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                    >
                      {addingTopicId === r.id ? "Loading..." : "Add"}
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      ) : (
        <form onSubmit={handleManualSubmit} className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <input
              placeholder="Themen-Name (z.B. Eigene Notizen)"
              className="w-full px-4 py-2.5 rounded-xl border dark:border-gray-700 dark:bg-gray-900 dark:text-white text-sm outline-none focus:ring-2 focus:ring-blue-500"
              value={manualName}
              onChange={(e) => setManualName(e.target.value)}
              required
            />
            <input
              placeholder="Kurze Beschreibung"
              className="w-full px-4 py-2.5 rounded-xl border dark:border-gray-700 dark:bg-gray-900 dark:text-white text-sm outline-none focus:ring-2 focus:ring-blue-500"
              value={manualDesc}
              onChange={(e) => setManualDesc(e.target.value)}
            />
          </div>
          
          <div className="flex flex-col md:flex-row gap-4 items-center">
             <div className="flex-1 w-full bg-gray-50 dark:bg-gray-900/50 border border-dashed dark:border-gray-700 rounded-xl p-3 flex flex-col items-center justify-center">
                <input 
                  type="file" 
                  accept=".pdf" 
                  id="pdf-upload"
                  className="hidden" 
                  onChange={(e) => setManualFile(e.target.files?.[0] || null)}
                />
                <label htmlFor="pdf-upload" className="cursor-pointer flex flex-col items-center">
                   <Plus size={20} className="text-gray-400 mb-1" />
                   <span className="text-[10px] font-bold text-gray-500">{manualFile ? manualFile.name : "PDF HOCHLADEN (Optional)"}</span>
                </label>
             </div>
             
             <div className="text-gray-400 text-[10px] font-bold uppercase">ODER</div>

             <input
              placeholder="Scraper URL (https://...)"
              className="flex-1 w-full px-4 py-2.5 rounded-xl border dark:border-gray-700 dark:bg-gray-900 dark:text-white text-sm outline-none focus:ring-2 focus:ring-blue-500"
              value={manualUrl}
              onChange={(e) => setManualUrl(e.target.value)}
            />

            <button 
              type="submit"
              disabled={adding}
              className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-2.5 rounded-xl font-bold text-sm transition-all shadow-lg shadow-blue-500/20 disabled:opacity-50"
            >
              Hinzufügen
            </button>
          </div>
        </form>
      )}
    </div>
  );
}

// CourseManager is the professor view for a single course.
// It has three tabs: Overview (stats + join code), Students, and Nodes (topics + Wikipedia articles).
export default function CourseManager() {
  const { courseId } = useParams<{ courseId: string }>();
  const navigate = useNavigate();
  
  // UI State
  const [tab, setTab] = useState<"overview" | "students" | "nodes">("overview");
  const [articleLang, setArticleLang] = useState<"en" | "de">("en");
  
  // Data State
  const [course, setCourse] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  // Stores fetched Wikipedia HTML per topic id to avoid re-fetching on tab switch
  const [topicContentById, setTopicContentById] = useState<Record<string, string>>({});
  const [loadingTopicId, setLoadingTopicId] = useState<string | null>(null);
  const [deletingTopicId, setDeletingTopicId] = useState<string | null>(null);
  
  // Topic Edit State
  const [isEditModalOpen, setIsEditModalOpen] = useState(false);
  const [editingTopic, setEditingTopic] = useState<any>(null);
  const [editName, setEditName] = useState("");
  const [editDesc, setEditDesc] = useState("");
  const [editFile, setEditFile] = useState<File | null>(null);
  const [editUrl, setEditUrl] = useState("");
  const [isUpdatingTopic, setIsUpdatingTopic] = useState(false);

  // Quiz Editor State
  const [isQuizModalOpen, setIsQuizModalOpen] = useState(false);
  const [selectedQuiz, setSelectedQuiz] = useState<any>(null);
  const [tempQuestions, setTempQuestions] = useState<any[]>([]);
  const [isSavingQuiz, setIsSavingQuiz] = useState(false);
  const [expandedMainTopics, setExpandedMainTopics] = useState<Record<string, boolean>>({});
  const [quickFilesByTopic, setQuickFilesByTopic] = useState<Record<string, File | null>>({});
  const [uploadingFileTopicId, setUploadingFileTopicId] = useState<string | null>(null);
  
  // Fetch Wikipedia article for a single topic.
  // Defined with useCallback to maintain reference stability-
  // this prevents the nodes useEffect from re-running unnecessarily.
  const loadTopicContent = useCallback(async (topicId: string, lang: string) => {
    try {
      setLoadingTopicId(topicId);
      const token = localStorage.getItem("token");
      
      const res = await axios.get(
        `http://localhost:3000/api/topics/${topicId}/content?lang=${lang}`,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      
      setTopicContentById((prev) => ({ 
        ...prev, 
        [topicId]: res.data.content || "No content found for this language." 
      }));
    } catch (err) {
      console.error("Failed to load topic content", err);
      setTopicContentById((prev) => ({ ...prev, [topicId]: "Error loading article." }));
    } finally {
      setLoadingTopicId(null);
    }
  }, []);

  // Fetch course data — called on mount and after adding/deleting a topic
  const fetchCourse = useCallback(async () => {
    try {
      setLoading(true);
      const token = localStorage.getItem("token");
      const res = await axios.get(`http://localhost:3000/api/courses/${courseId}`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setCourse(res.data);
    } catch (err) {
      console.error("Failed to fetch course", err);
    } finally {
      setLoading(false);
    }
  }, [courseId]);
 
  useEffect(() => {
    if (courseId) fetchCourse();
  }, [courseId, fetchCourse]);

  // Trigger Wikipedia content loading when the Nodes tab becomes active or the language changes.
  useEffect(() => {
    const nodes = course?.topics || [];
    if (tab === "nodes" && nodes.length > 0) {
      nodes.forEach((node: any) => {
        // load content only if we haven't already fetched it for this topic and language
        if (!topicContentById[node.id]) {
          loadTopicContent(node.id, articleLang);
        }
      });
    }
    // IMPORTANT: topicContentById is NOT in dependencies to avoid re-triggering
  }, [tab, articleLang, course?.topics, loadTopicContent]);

  // Delete a topic after confirmation — refreshes the course after
  const handleDeleteTopic = async (topicId: string, topicName: string) => {
    if (!window.confirm(`Delete topic "${topicName}"? This cannot be undone.`)) return;
    setDeletingTopicId(topicId);
    try {
      const token = localStorage.getItem("token");
      await axios.delete(`http://localhost:3000/api/topics/${topicId}`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      // Remove cached content for this topic and refresh the course
      setTopicContentById((prev) => {
        const next = { ...prev };
        delete next[topicId];
        return next;
      });
      await fetchCourse();
    } catch (err) {
      console.error("Failed to delete topic", err);
      alert("Failed to delete topic.");
    } finally {
      setDeletingTopicId(null);
    }
  }; 

  // Nutzt die KI, um für ein Thema Zusammenfassung und Quizzes zu generieren
  const handleEnrichTopic = async (topicId: string) => {
    try {
      setLoadingTopicId(topicId); // Wir nutzen den gleichen Lade-Status
      const token = localStorage.getItem("token");
      await axios.post(
        `http://localhost:3000/api/topics/${topicId}/enrich`,
        {},
        { headers: { Authorization: `Bearer ${token}` } }
      );
      fetchCourse(); // Neu laden, um die Zusammenfassung zu sehen
      alert("KI-Analyse abgeschlossen!");
    } catch (err) {
      console.error("Fehler beim KI-Enrichment:", err);
      alert("KI-Analyse fehlgeschlagen.");
    } finally {
      setLoadingTopicId(null);
    }
  };

  // Öffnet den Quiz-Editor
  const handleOpenQuizEditor = (quiz: any) => {
    setSelectedQuiz(quiz);
    setTempQuestions(quiz.questions || []);
    setIsQuizModalOpen(true);
  };

  // Öffnet das Edit-Modal für ein Thema
  const handleEditOpen = (topic: any) => {
    setEditingTopic(topic);
    setEditName(topic.name);
    setEditDesc(topic.description || "");
    setEditUrl(""); // Reset files/urls on open
    setEditFile(null);
    setIsEditModalOpen(true);
  };

  // Speichert die Änderungen an einem Thema (Name, Beschreibung, PDF-Upload)
  const handleUpdateTopic = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!editingTopic) return;
    setIsUpdatingTopic(true);

    try {
      const token = localStorage.getItem("token");
      const formData = new FormData();
      formData.append("name", editName);
      formData.append("description", editDesc);
      if (editUrl) formData.append("sourceUrl", editUrl);
      if (editFile) formData.append("pdf", editFile);

      await axios.put(`http://localhost:3000/api/topics/${editingTopic.id}`, formData, {
        headers: { 
          Authorization: `Bearer ${token}`,
          "Content-Type": "multipart/form-data" 
        }
      });

      setIsEditModalOpen(false);
      fetchCourse();
      alert("Thema erfolgreich aktualisiert!");
    } catch (err) {
      console.error("Failed to update topic", err);
      alert("Fehler beim Aktualisieren.");
    } finally {
      setIsUpdatingTopic(false);
    }
  };

  // Speichert die Änderungen am Quiz in der Datenbank
  const handleSaveQuiz = async () => {
    if (!selectedQuiz) return;
    setIsSavingQuiz(true);
    try {
      const token = localStorage.getItem("token");
      await axios.put(
        `http://localhost:3000/api/topics/quizzes/${selectedQuiz.id}`,
        { questions: tempQuestions },
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setIsQuizModalOpen(false);
      fetchCourse(); // Daten neu laden
      alert("Quiz erfolgreich gespeichert!");
    } catch (err) {
      console.error("Failed to save quiz", err);
      alert("Fehler beim Speichern des Quiz.");
    } finally {
      setIsSavingQuiz(false);
    }
  };

  // Löscht ein Quiz komplett
  const handleDeleteQuiz = async (quizId: string) => {
    if (!window.confirm("Dieses Quiz wirklich löschen?")) return;
    try {
      const token = localStorage.getItem("token");
      await axios.delete(`http://localhost:3000/api/topics/quizzes/${quizId}`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setIsQuizModalOpen(false);
      fetchCourse();
    } catch (err) {
      console.error("Failed to delete quiz", err);
    }
  };

  // Aktualisiert die Voraussetzungen eines Themas in der Datenbank
  const handleUpdatePrerequisites = async (topicId: string, prerequisiteIds: string[]) => {
    try {
      const token = localStorage.getItem("token");
      if (!token) return;

      await axios.put(
        `http://localhost:3000/api/topics/${topicId}`,
        { prerequisiteIds },
        { headers: { Authorization: `Bearer ${token}` } }
      );
      // Den gesamten Kurs neu laden, um die neuen Beziehungen sofort anzuzeigen
      fetchCourse(); 
    } catch (err) {
      console.error("Fehler beim Aktualisieren der Hierarchie:", err);
      alert("Konnte Themen nicht verknüpfen.");
    }
  };

  const handleQuickSubtopicFileUpload = async (topic: any) => {
    const file = quickFilesByTopic[topic.id];
    if (!file) return;

    setUploadingFileTopicId(topic.id);
    try {
      const token = localStorage.getItem("token");
      const formData = new FormData();
      formData.append("name", topic.name || "");
      formData.append("description", topic.description || "");
      formData.append("pdf", file);

      await axios.put(`http://localhost:3000/api/topics/${topic.id}`, formData, {
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "multipart/form-data"
        }
      });

      setQuickFilesByTopic((prev) => ({ ...prev, [topic.id]: null }));
      setTopicContentById((prev) => {
        const next = { ...prev };
        delete next[topic.id];
        return next;
      });
      fetchCourse();
    } catch (err) {
      console.error("Failed quick file upload", err);
      alert("Datei konnte nicht hochgeladen werden.");
    } finally {
      setUploadingFileTopicId(null);
    }
  };
  if (loading) {
    return <div className="text-center py-32 text-gray-500 font-medium">Loading course details...</div>;
  }
 
  if (!course) {
    return (
      <div className="flex flex-col items-center justify-center py-32 gap-4">
        <p className="text-gray-500">Course not found or access denied.</p>
        <button onClick={() => navigate("/dashboard")} className="text-blue-600 font-bold hover:underline">
          ← Back to Dashboard
        </button>
      </div>
    );
  }

  // DATA MAPPING: Prepare variables for rendering
  const students = course.students || []; 
  const nodes = course.topics || [];
  const nodeIds = new Set(nodes.map((n: any) => n.id));
  const childrenByParentId = new Map<string, any[]>();
  const parentByChildId = new Map<string, string>();

  nodes.forEach((node: any) => {
    const parentId = node.prerequisites?.find((p: any) => nodeIds.has(p.id))?.id;
    if (!parentId) return;
    parentByChildId.set(node.id, parentId);
    const children = childrenByParentId.get(parentId) || [];
    children.push(node);
    childrenByParentId.set(parentId, children);
  });

  const topLevelNodes = nodes.filter((node: any) => !parentByChildId.has(node.id));

  const sortedNodes: any[] = [];
  const visited = new Set<string>();

  topLevelNodes
    .sort((a: any, b: any) => a.name.localeCompare(b.name))
    .forEach((mainNode: any) => {
      sortedNodes.push(mainNode);
      visited.add(mainNode.id);

      const children = (childrenByParentId.get(mainNode.id) || [])
        .sort((a, b) => a.name.localeCompare(b.name));
      children.forEach((child) => {
        sortedNodes.push(child);
        visited.add(child.id);
      });
    });

  nodes.forEach((node: any) => {
    if (!visited.has(node.id)) sortedNodes.push(node);
  });

  // Delete course and redirect to dashboard.
  // Topics are detached (courseId set to null) but not deleted — quizzes are preserved for reuse.
  const handleDeleteCourse = async () => {
    if (!window.confirm(`Are you sure you want to delete "${course.title}"? This cannot be undone.`)) return;

    try {
      const token = localStorage.getItem("token");
      await axios.delete(`http://localhost:3000/api/courses/${courseId}`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      navigate("/dashboard");
    } catch (err) {
      console.error("Failed to delete course", err);
      alert("Failed to delete course.");
    }
  };

  // Helper function to render the content of the currently selected tab.
  const renderTabContent = () => {
    switch (tab) {
      case "overview":
        return (
          <div className="flex flex-col gap-6 animate-in fade-in duration-300">
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              {[
                { label: "Students", value: students.length, icon: Users },
                { label: "Nodes", value: nodes.length, icon: BookOpen },
                { label: "Visibility", value: course.isPublic ? "Public" : "Private", icon: Globe },
              ].map(({ label, value, icon: Icon }) => (
                <div key={label} className="bg-white dark:bg-gray-800 rounded-2xl border dark:border-gray-700 p-5 flex items-center gap-4 shadow-sm">
                  <div className="w-10 h-10 rounded-xl flex items-center justify-center bg-blue-50 dark:bg-blue-900/30 text-blue-600">
                    <Icon size={20} />
                  </div>
                  <div>
                    <p className="text-xs text-gray-400 font-medium uppercase tracking-wider">{label}</p>
                    <p className="text-xl font-bold dark:text-white">{value}</p>
                  </div>
                </div>
              ))}
            </div>

            {/* Join code section — professors share this with students to enroll */}
            <div className="bg-white dark:bg-gray-800 rounded-2xl p-6 border dark:border-gray-700 shadow-sm">
              <h3 className="text-sm font-bold mb-4 dark:text-white uppercase tracking-wider">Access Configuration</h3>
              <div className="flex justify-between items-center p-4 bg-gray-50 dark:bg-gray-900/50 rounded-xl border dark:border-gray-700">
                <div>
                  <p className="text-xs text-gray-500">Student Join Code</p>
                  <p className="text-lg font-mono font-bold text-blue-600 uppercase">{course.joinCode}</p>
                </div>
                <CopyBtn text={course.joinCode} />
              </div>
            </div>
          </div>
        );

      case "students":
        return (
          <div className="flex flex-col gap-3 animate-in fade-in">
            <p className="text-sm text-gray-500 mb-2">{students.length} students enrolled</p>
            {students.length === 0 ? (
              <div className="text-center py-10 bg-gray-50 rounded-2xl border-2 border-dashed text-gray-400">
                No students joined yet.
              </div>
            ) : (
              students.map((s: any) => (
                <div key={s.id} className="bg-white dark:bg-gray-800 rounded-xl border dark:border-gray-700 p-4 flex items-center justify-between shadow-sm">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-full bg-gray-200 dark:bg-gray-700" />
                    <p className="font-semibold dark:text-gray-200">{s.email}</p>
                  </div>
                </div>
              ))
            )}
          </div>
        );

      case "nodes":
        return (
          <div className="flex flex-col gap-4 animate-in fade-in">
            <div className="flex items-center justify-between bg-white dark:bg-gray-800 p-4 rounded-xl border dark:border-gray-700">
              <p className="text-sm font-medium text-gray-500">{nodes.length} topics defined</p>
              <div className="flex gap-1 p-1 bg-gray-100 dark:bg-gray-900 rounded-lg">
                {(['en', 'de'] as const).map((l) => (
                  <button
                    key={l}
                    onClick={() => { setTopicContentById({}); setArticleLang(l); }}
                    className={`px-3 py-1 rounded-md text-xs font-bold transition-all ${articleLang === l ? 'bg-white dark:bg-gray-700 shadow-sm text-blue-600' : 'text-gray-400'}`}
                  >
                    {l.toUpperCase()}
                  </button>
                ))}
              </div>
            </div>

            {/* Add topic panel — always visible at the top of the nodes tab */}
            <AddTopicPanel
              courseId={courseId!}
              onTopicAdded={(newTopics) => {
                const topics = Array.isArray(newTopics) ? newTopics.filter(Boolean) : [];

                // Immediate UI update (optimistic): add new topics instantly
                setCourse((prev: any) => {
                  if (!prev) return prev;
                  const existing = prev.topics || [];
                  const existingIds = new Set(existing.map((t: any) => t.id));
                  const merged = [...existing];
                  topics.forEach((t: any) => {
                    if (t?.id && !existingIds.has(t.id)) {
                      merged.push(t);
                      existingIds.add(t.id);
                    }
                  });
                  return { ...prev, topics: merged };
                });

                // Clear cached article HTML for new topics
                setTopicContentById((prev) => {
                  const next = { ...prev };
                  topics.forEach((t: any) => {
                    if (t?.id) delete next[t.id];
                  });
                  return next;
                });

                // Background refresh to sync full server state
                fetchCourse();
              }}
            />
            
            {/* Topic cards */}
            {nodes.length === 0 ? (
              <div className="text-center py-10 bg-gray-50 dark:bg-gray-800/50 rounded-2xl border-2 border-dashed border-gray-200 dark:border-gray-700 text-gray-400">
                No topics yet — use the panel above to add your first one.
              </div>
            ) : (
              sortedNodes.map((node: any) => {
                const parentId = parentByChildId.get(node.id);
                const isSubtopic = Boolean(parentId);
                const isVisible = !isSubtopic || expandedMainTopics[parentId!] !== false;
                const subtopicCount = (childrenByParentId.get(node.id) || []).length;
                const isExpanded = expandedMainTopics[node.id] !== false;

                if (!isVisible) return null;

                return (
                <div
                  key={node.id}
                  className={`bg-white dark:bg-gray-800 rounded-2xl border dark:border-gray-700 p-6 shadow-sm ${isSubtopic ? "ml-6 md:ml-10 border-l-4 border-l-blue-300 dark:border-l-blue-800" : ""}`}
                >
                  <div className="flex items-start justify-between mb-4">
                    <div>
                      <div className="flex items-center gap-2 mb-1">
                        <h4 className="text-lg font-bold dark:text-white">{node.name}</h4>
                        {isSubtopic && (
                          <span className="px-2 py-0.5 bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400 text-[9px] font-extrabold rounded-md uppercase tracking-wider border border-blue-200 dark:border-blue-900">
                            Subtopic
                          </span>
                        )}
                        {/* Lila Badge wenn die KI bereits am Werk war */}
                        {node.description?.includes("[KI-ZUSAMMENFASSUNG]") && (
                          <span className="px-2 py-0.5 bg-purple-100 dark:bg-purple-900/30 text-purple-600 dark:text-purple-400 text-[9px] font-extrabold rounded-md uppercase tracking-wider border border-purple-200 dark:border-purple-800">
                            ✨ AI Enriched
                          </span>
                        )}
                        {!isSubtopic && subtopicCount > 0 && (
                          <button
                            onClick={() =>
                              setExpandedMainTopics((prev) => ({
                                ...prev,
                                [node.id]: !isExpanded
                              }))
                            }
                            className="ml-2 inline-flex items-center gap-1 px-2.5 py-1 rounded-md text-[10px] font-bold uppercase tracking-wide text-blue-700 dark:text-blue-300 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-900 hover:bg-blue-100 dark:hover:bg-blue-900/40 transition-colors"
                          >
                            {isExpanded ? <ChevronDown size={13} /> : <ChevronRight size={13} />}
                            {subtopicCount} Subtopic{subtopicCount > 1 ? "s" : ""}
                          </button>
                        )}
                      </div>
                      <p className="text-sm text-gray-500 mt-1 leading-relaxed">
                        {node.description || "No description provided."}
                      </p>
                      
                      {/* --- Prerequisites UI (Roadmap Logik) --- */}
                      <div className="mt-4 pt-4 border-t dark:border-gray-700">
                        <p className="text-xs font-bold text-gray-400 uppercase mb-2">Voraussetzungen (Roadmap-Link)</p>
                        <div className="flex flex-wrap gap-2">
                          {/* Zeige alle ANDEREN Themen dieses Kurses als Verknüpfungs-Option an */}
                          {nodes.filter((other: any) => other.id !== node.id).map((other: any) => {
                            // Prüfen, ob dieses 'other' Thema bereits eine Voraussetzung für das aktuelle 'node' Thema ist
                            const isPrereq = node.prerequisites?.some((p: any) => p.id === other.id);
                            
                            return (
                              <button
                                key={other.id}
                                onClick={() => {
                                  const currentIds = node.prerequisites?.map((p: any) => p.id) || [];
                                  const newIds = isPrereq 
                                    ? currentIds.filter((id: string) => id !== other.id) 
                                    : [...currentIds, other.id];
                                  handleUpdatePrerequisites(node.id, newIds);
                                }}
                                className={`px-3 py-1.5 rounded-full text-[10px] font-bold tracking-wide uppercase transition-all ${
                                  isPrereq 
                                    ? "bg-blue-600 border-blue-600 text-white shadow-md shadow-blue-500/20" 
                                    : "bg-gray-50 dark:bg-gray-900 border-gray-200 dark:border-gray-700 text-gray-500 hover:border-blue-300 dark:hover:border-blue-900"
                                } border`}
                              >
                                {isPrereq ? "✓ " : "+ "} {other.name}
                              </button>
                            );
                          })}
                          {nodes.length <= 1 && (
                            <p className="text-xs text-gray-400 italic">No other topics to link yet.</p>
                          )}
                        </div>
                      </div>
                      
                      {/* --- KI-Quiz (Nur falls vorhanden) --- */}
                      {node.quizzes?.length > 0 && (
                        <div className="mt-4 p-4 bg-green-50 dark:bg-green-900/10 border border-green-100 dark:border-green-800/30 rounded-xl">
                          <div className="flex items-center justify-between mb-2">
                            <p className="text-[10px] font-bold text-green-600 dark:text-green-500 uppercase tracking-widest">
                              Vorhandene Quizzes
                            </p>
                            <span className="text-[10px] font-bold px-2 py-0.5 bg-green-200 dark:bg-green-900 text-green-800 dark:text-green-300 rounded-full">
                              {node.quizzes.length} Modul(e)
                            </span>
                          </div>
                          <button 
                            onClick={() => handleOpenQuizEditor(node.quizzes[0])}
                            className="w-full py-2 bg-green-600 hover:bg-green-700 text-white text-xs font-bold rounded-lg transition-colors shadow-sm"
                          >
                            Quiz jetzt ansehen & bearbeiten
                          </button>
                        </div>
                      )}
                    </div>
 
                    {/* Delete topic button */}
                    <div className="flex flex-col gap-2">
                       <button
                        onClick={() => handleEditOpen(node)}
                        className="flex-shrink-0 ml-4 flex items-center justify-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-blue-600 border border-blue-200 dark:border-blue-900 rounded-lg hover:bg-blue-50 dark:hover:bg-blue-900/20 transition-colors"
                      >
                        Bearbeiten
                      </button>

                      {isSubtopic && (
                        <div className="ml-4 flex flex-col gap-1">
                          <input
                            type="file"
                            accept=".pdf,application/pdf"
                            onChange={(e) => {
                              const file = e.target.files?.[0] || null;
                              setQuickFilesByTopic((prev) => ({ ...prev, [node.id]: file }));
                            }}
                            className="text-[10px] text-gray-500 max-w-[190px]"
                          />
                          <button
                            onClick={() => handleQuickSubtopicFileUpload(node)}
                            disabled={!quickFilesByTopic[node.id] || uploadingFileTopicId === node.id}
                            className="flex items-center justify-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-emerald-700 border border-emerald-200 rounded-lg hover:bg-emerald-50 transition-colors disabled:opacity-40"
                          >
                            {uploadingFileTopicId === node.id ? "Uploading..." : "Datei hinzufügen"}
                          </button>
                        </div>
                      )}

                      <button
                        onClick={() => handleDeleteTopic(node.id, node.name)}
                        disabled={deletingTopicId === node.id}
                        className="flex-shrink-0 ml-4 flex items-center justify-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-red-500 border border-red-200 dark:border-red-900 rounded-lg hover:bg-red-50 dark:hover:bg-red-900/20 transition-colors disabled:opacity-40"
                      >
                        <Trash2 size={13} />
                        {deletingTopicId === node.id ? "Deleting..." : "Entfernen"}
                      </button>
                    </div>
                    
                    {/* KI-Enrichment Button */}
                    <button
                      onClick={() => handleEnrichTopic(node.id)}
                      disabled={loadingTopicId === node.id || (!node.content && !node.wikidataId)}
                      title={(!node.content && !node.wikidataId) ? "Kein Inhalt oder Wiki-Link zum Analysieren da" : ""}
                      className="flex-shrink-0 ml-2 flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-purple-600 border border-purple-200 dark:border-purple-900 rounded-lg hover:bg-purple-50 dark:hover:bg-purple-900/20 transition-colors disabled:opacity-40"
                    >
                      ✨ {loadingTopicId === node.id ? "Analysiere..." : "KI: Zusammenfassung & Quiz"}
                    </button>
                  </div>
 
                  <div className="bg-gray-50 dark:bg-gray-900/50 rounded-xl p-4 border dark:border-gray-700">
                    <div className="flex items-center justify-between mb-3">
                      <span className="text-xs font-bold text-gray-400 uppercase">Wikipedia Content</span>
                      {loadingTopicId === node.id && (
                        <span className="text-xs text-blue-500 animate-pulse italic">Fetching...</span>
                      )}
                    </div>
 
                    <div
                      className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed max-h-60 overflow-y-auto pr-2 custom-scrollbar wikipedia-article-content"
                      dangerouslySetInnerHTML={{
                        __html: topicContentById[node.id] || "Loading article..."
                      }}
                    />
                  </div>
                </div>
                );
              })
            )}
          </div>
        );
      default: return null;
    }
  };
 
  return (
    <div className="max-w-4xl mx-auto px-4 py-10">
      {/* Top Navigation */}
      <button 
        onClick={() => navigate("/dashboard")} 
        className="group flex items-center gap-2 text-sm font-semibold mb-8 text-gray-400 hover:text-blue-600 transition-colors"
      >
        <ArrowLeft size={16} className="group-hover:-translate-x-1 transition-transform" /> 
        Back to Dashboard
      </button>

      {/* Course Header */}
      <div className="mb-10 flex justify-between items-start">
        <div>
          <h1 className="text-4xl font-extrabold dark:text-white mb-2 tracking-tight">{course.title}</h1>
          <p className="text-lg text-gray-500 max-w-2xl">{course.description || "Add a description to help students understand this course."}</p>
        </div>
        <button
          onClick={handleDeleteCourse}
          className="flex items-center gap-2 px-4 py-2 text-sm font-semibold text-red-500 border border-red-200 rounded-xl hover:bg-red-50 dark:hover:bg-red-900/20 transition-colors"
        >
          <Trash2 size={16} /> Delete Course
        </button>
      </div>

      {/* Tab Switcher */}
      <div className="flex gap-1 mb-8 rounded-2xl p-1.5 bg-gray-100/50 dark:bg-gray-900/50 border dark:border-gray-700 overflow-x-auto">
        <TabBtn label="Overview" active={tab === "overview"} onClick={() => setTab("overview")} />
        <TabBtn label={`Students (${students.length})`} active={tab === "students"} onClick={() => setTab("students")} />
        <TabBtn label={`Nodes (${nodes.length})`} active={tab === "nodes"} onClick={() => setTab("nodes")} />
      </div>

      {/* Main Tab Content */}
      <main className="min-h-[400px]">
        {renderTabContent()}
      </main>

      {/* --- QUIZ EDITOR MODAL --- */}
      {isQuizModalOpen && selectedQuiz && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in transition-all">
          <div className="bg-white dark:bg-gray-800 w-full max-w-2xl max-h-[90vh] rounded-3xl shadow-2xl overflow-hidden flex flex-col border dark:border-gray-700">
            {/* Modal Header */}
            <div className="p-6 border-b dark:border-gray-700 flex justify-between items-center bg-gray-50 dark:bg-gray-900/50">
              <div>
                <h3 className="text-xl font-bold dark:text-white">Quiz Editor ✨</h3>
                <p className="text-xs text-gray-400 mt-1">Überprüfe und bearbeite die KI-generierten Fragen</p>
              </div>
              <button 
                onClick={() => setIsQuizModalOpen(false)}
                className="p-2 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-full transition-colors"
              >
                <X size={20} className="text-gray-500" />
              </button>
            </div>

            {/* Modal Content (Scrollable) */}
            <div className="flex-1 overflow-y-auto p-6 space-y-8 custom-scrollbar">
              {tempQuestions.map((q, qIdx) => (
                <div key={qIdx} className="relative p-5 bg-gray-50 dark:bg-gray-900/40 rounded-2xl border dark:border-gray-700">
                  <div className="absolute -top-3 -left-3 w-8 h-8 bg-purple-600 text-white rounded-lg flex items-center justify-center font-bold text-sm shadow-lg">
                    {qIdx + 1}
                  </div>
                  
                  {/* Question Text */}
                  <div className="mb-4">
                    <label className="text-[10px] font-bold text-gray-400 uppercase mb-1 block">Frage</label>
                    <input 
                      type="text"
                      value={q.question}
                      onChange={(e) => {
                        const newQ = [...tempQuestions];
                        newQ[qIdx].question = e.target.value;
                        setTempQuestions(newQ);
                      }}
                      className="w-full bg-white dark:bg-gray-800 border dark:border-gray-700 rounded-xl px-4 py-2 text-sm focus:ring-2 focus:ring-purple-500 outline-none transition-all dark:text-white"
                    />
                  </div>

                  {/* Options */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                    {q.options.map((opt: string, oIdx: number) => (
                      <div key={oIdx}>
                        <label className="text-[9px] font-bold text-gray-400 uppercase mb-1 block">Option {oIdx + 1}</label>
                        <input 
                          type="text"
                          value={opt}
                          onChange={(e) => {
                            const newQ = [...tempQuestions];
                            newQ[qIdx].options[oIdx] = e.target.value;
                            setTempQuestions(newQ);
                          }}
                          className={`w-full bg-white dark:bg-gray-800 border rounded-xl px-4 py-2 text-xs focus:ring-2 focus:ring-purple-500 outline-none transition-all dark:text-white ${
                            q.answer === opt ? 'border-green-500 ring-1 ring-green-500/20' : 'dark:border-gray-700'
                          }`}
                        />
                      </div>
                    ))}
                  </div>

                  {/* Correct Answer Selector */}
                  <div className="mt-4 flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <span className="text-[10px] font-bold text-gray-400 uppercase">Richtige Lösung:</span>
                      <select 
                        value={q.answer}
                        onChange={(e) => {
                          const newQ = [...tempQuestions];
                          newQ[qIdx].answer = e.target.value;
                          setTempQuestions(newQ);
                        }}
                        className="bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400 text-xs font-bold px-3 py-1 rounded-lg outline-none cursor-pointer"
                      >
                        {q.options.map((opt: string) => <option key={opt} value={opt}>{opt}</option>)}
                      </select>
                    </div>

                    <button 
                      onClick={() => {
                        const newQ = tempQuestions.filter((_, i) => i !== qIdx);
                        setTempQuestions(newQ);
                      }}
                      className="text-red-500 hover:text-red-700 p-2 transition-colors"
                    >
                      <Trash2 size={16} />
                    </button>
                  </div>
                </div>
              ))}

              <button 
                onClick={() => {
                  setTempQuestions([...tempQuestions, { question: "Neue Frage?", options: ["A", "B", "C", "D"], answer: "A" }]);
                }}
                className="w-full py-3 border-2 border-dashed border-gray-200 dark:border-gray-700 rounded-2xl text-gray-400 hover:text-purple-500 hover:border-purple-300 transition-all flex items-center justify-center gap-2 font-bold text-sm"
              >
                <Plus size={18} /> Frage hinzufügen
              </button>
            </div>

            {/* Modal Footer */}
            <div className="p-6 border-t dark:border-gray-700 flex gap-3 bg-gray-50 dark:bg-gray-900/50">
              <button 
                onClick={() => handleDeleteQuiz(selectedQuiz.id)}
                className="px-4 py-2 text-xs font-bold text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-xl transition-colors"
              >
                Quiz löschen
              </button>
              <div className="flex-1" />
              <button 
                onClick={() => setIsQuizModalOpen(false)}
                className="px-6 py-2 text-sm font-bold text-gray-500 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-xl transition-colors"
              >
                Abbrechen
              </button>
              <button 
                onClick={handleSaveQuiz}
                disabled={isSavingQuiz}
                className="px-8 py-2 bg-purple-600 hover:bg-purple-700 disabled:opacity-50 text-white text-sm font-bold rounded-xl transition-all shadow-lg shadow-purple-500/20"
              >
                {isSavingQuiz ? "Speichert..." : "Änderungen speichern"}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* --- TOPIC EDIT MODAL --- */}
      {isEditModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in transition-all">
          <div className="bg-white dark:bg-gray-800 w-full max-w-xl rounded-3xl shadow-2xl overflow-hidden flex flex-col border dark:border-gray-700">
            <form onSubmit={handleUpdateTopic}>
              <div className="p-6 border-b dark:border-gray-700 flex justify-between items-center">
                <h3 className="text-xl font-bold dark:text-white">Thema bearbeiten</h3>
                <button type="button" onClick={() => setIsEditModalOpen(false)} className="p-2 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-full transition-colors">
                  <X size={20} className="text-gray-500" />
                </button>
              </div>

              <div className="p-6 space-y-4">
                <div>
                  <label className="text-[10px] font-bold text-gray-400 uppercase mb-1 block">Name</label>
                  <input
                    value={editName}
                    onChange={(e) => setEditName(e.target.value)}
                    className="w-full px-4 py-2.5 rounded-xl border dark:border-gray-700 dark:bg-gray-900 dark:text-white text-sm outline-none focus:ring-2 focus:ring-blue-500"
                    required
                  />
                </div>
                <div>
                  <label className="text-[10px] font-bold text-gray-400 uppercase mb-1 block">Beschreibung</label>
                  <textarea
                    value={editDesc}
                    onChange={(e) => setEditDesc(e.target.value)}
                    className="w-full px-4 py-2.5 rounded-xl border dark:border-gray-700 dark:bg-gray-900 dark:text-white text-sm outline-none focus:ring-2 focus:ring-blue-500 min-h-[80px]"
                  />
                </div>

                <div className="pt-4 border-t dark:border-gray-700">
                   <p className="text-[10px] font-bold text-blue-500 uppercase mb-3">Inhalt aktualisieren (Optional)</p>
                   <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div className="bg-gray-50 dark:bg-gray-900/50 border border-dashed dark:border-gray-700 rounded-xl p-4 flex flex-col items-center justify-center">
                        <input type="file" accept=".pdf" id="edit-pdf" className="hidden" onChange={(e) => setEditFile(e.target.files?.[0] || null)} />
                        <label htmlFor="edit-pdf" className="cursor-pointer flex flex-col items-center">
                           <Plus size={20} className="text-gray-400 mb-1" />
                           <span className="text-[10px] font-bold text-gray-500">{editFile ? editFile.name : "NEUES PDF HOCHLADEN"}</span>
                        </label>
                      </div>
                      <input
                        placeholder="Neue Scraper URL"
                        className="w-full px-4 py-2.5 rounded-xl border dark:border-gray-700 dark:bg-gray-900 dark:text-white text-sm outline-none focus:ring-2 focus:ring-blue-500 h-fit"
                        value={editUrl}
                        onChange={(e) => setEditUrl(e.target.value)}
                      />
                   </div>
                   <p className="text-[9px] text-gray-400 mt-2 italic">Hinweis: Neue PDFs oder URLs werden zum bestehenden Wissen (z.B. Wikipedia) <b>hinzugefügt</b>, um die KI-Zusammenfassung zu verbessern.</p>
                </div>
              </div>

              <div className="p-6 border-t dark:border-gray-700 flex justify-end gap-3 bg-gray-50 dark:bg-gray-900/50">
                <button type="button" onClick={() => setIsEditModalOpen(false)} className="px-6 py-2 text-sm font-bold text-gray-500 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-xl transition-colors">Abbrechen</button>
                <button
                  type="submit"
                  disabled={isUpdatingTopic}
                  className="px-8 py-2 bg-blue-600 hover:bg-blue-700 text-white text-sm font-bold rounded-xl transition-all shadow-lg shadow-blue-500/20 disabled:opacity-50"
                >
                  {isUpdatingTopic ? "Speichert..." : "Speichern"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
